{% set name = "ConservedWaterSearch" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 97abe3dd122e57ce2496ba897e25e4f27f31ed383631c0d138db58905b1a31bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.22
    - scikit-learn >=1.3

test:
  imports:
    - ConservedWaterSearch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JecaTosovic/ConservedWaterSearch
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ConservedWaterSearch.readthedocs.io/
  dev_url: https://github.com/JecaTosovic/ConservedWaterSearch
  summary: Determination of conserved waters from MD trajectories for drug design and materials science.

extra:
  recipe-maintainers:
    - JecaTosovic
    - DomFijan
